"""DAG-based analysis materialization pipeline.

All generated outputs live under the configured knowledgebase-backed analysis
artefact root. Human-readable markdown summaries generated by the map steps
land there as well, rather than in tracked docs.
"""

from __future__ import annotations

from datetime import date, timedelta
from pathlib import Path
from typing import Any, Sequence

from .core.dag import DAG, Step
from lynchpin.core.io import resolve_analysis_path, save_json
from .ecosystem.current_state import run_current_state_analysis
from .active.ai_attribution import run_active_ai_attribution
from .active.git_facts import run_active_git_facts
from .active.snapshot import run_active_project_snapshot
from .active.substrate_promote import (
    SOURCE_AI_WORK_EVENTS,
    SOURCE_COMMITS,
    SOURCE_EVIDENCE_GRAPH,
    SOURCE_FILE_CHANGES,
    SOURCE_MACHINE,
    SOURCE_MACHINE_EXPERIMENTS,
    SOURCE_MACHINE_GPU,
    SOURCE_MACHINE_NETWORK,
    SOURCE_MACHINE_CGROUP_MEMORY,
    SOURCE_MACHINE_KILL_EVENT,
    SOURCE_MACHINE_PROCESS_IO_DELTA,
    SOURCE_MACHINE_PROCESS_MEMORY,
    SOURCE_MACHINE_SERVICE_STATE,
    SOURCE_PR_REVIEW,
    SOURCE_SYMBOLS,
    SOURCE_WORK_OBSERVATIONS,
    run_substrate_promote,
)
from .change.commit_capsules import run_active_commit_semantics
from .change.work_packages import run_active_work_packages
from .code_index.code_inventory import run_active_code_inventory
from .code_index.python_analysis import run_active_python_complexity, run_active_python_import_graph
from .code_index.rust_workspace import run_active_rust_graph
from .code_index.symbol_diffs import run_active_symbol_diffs
from .code_index.symbol_index import run_active_symbol_index
from .frontier.ci_health import run_active_ci_health
from .frontier.github_frontier import run_active_github_frontier
from .interpretation.python_dependency_hygiene import run_active_python_dependency_hygiene
from .interpretation.rust_dependency_hygiene import run_active_rust_dependency_hygiene
from .interpretation.semantic_static_findings import run_active_semantic_static_findings
from .interpretation.shape import run_active_guardrails, run_active_hotspots
from .interpretation.structural_findings import run_active_structural_findings
from .interpretation.velocity_windows import run_project_velocity_windows
from .code_history_claims import write_code_history_claims
from .keylog import write_keylog_analysis
from .machine.attribution import write_below_attribution_analysis
from .machine.attribution_candidates import write_machine_attribution_candidates
from .machine.attribution_claims import write_machine_attribution_claims
from .machine.assumption_checks import write_machine_assumption_checks
from .machine.baselines import write_machine_observational_baselines
from .machine.below_export_handoff import write_below_export_handoff
from .machine.benchmark_manifest_bundle import write_machine_benchmark_manifest_bundle
from .machine.benchmark_execution_handoff import write_machine_benchmark_execution_handoff
from .machine.benchmark_plans import write_machine_benchmark_plans
from .machine.benchmark_preflight import write_machine_benchmark_preflight
from .machine.calibration import write_machine_calibration
from .machine.below import write_below_analysis
from .machine.command_performance import write_command_performance_analysis
from .machine.comparisons import write_machine_comparisons
from .machine.context import write_machine_context_analysis
from .machine.dataset_diagnostics import write_machine_dataset_diagnostics
from .machine.derivation_inventory import write_machine_derivation_inventory
from .machine.devshell import write_devshell_performance_analysis
from .machine.episodes import write_machine_episode_analysis
from .machine.experiment_manifest_diagnostics import write_machine_experiment_manifest_diagnostics
from .machine.pressure_incidents import write_machine_pressure_incidents
from .machine.experiments import write_machine_experiment_claims
from .machine.feature_frames import write_machine_feature_frames
from .machine.gap_summary import write_gap_summary_analysis
from .machine.instrumentation_gaps import write_machine_instrumentation_gaps
from .machine.matched_designs import write_machine_matched_designs
from .machine.measurement_system import write_machine_measurement_system
from .machine.mechanisms import write_machine_mechanisms
from .machine.mining import write_machine_mining
from .machine.negative_controls import write_machine_negative_controls
from .machine.observational import write_observational_command_deltas
from .machine.readiness import write_machine_analysis_readiness
from .machine.states import write_machine_work_state_analysis
from .machine.support_assessment import write_machine_support_assessment
from .machine.telemetry import write_machine_telemetry_analysis
from .machine.validation_design import write_machine_validation_design
from .machine.work_observations import write_work_observation_analysis
from .anomaly_crossref import write_report as write_anomaly_crossref_report
from .life_phase import write_report as write_life_phase_report
from .productivity_predictors import write_report as write_productivity_predictors_report
from .substance_health import write_report as write_substance_health_report
from .burnout_warning import write_report as write_burnout_warning_report
from .ai_session_efficiency import write_report as write_ai_session_efficiency_report
from .operator_daily import operator_daily_matrix
from .sinex import temporal as sinex_temporal
from .workflow_mechanics import write_workflow_mechanics_report


def _out(name: str) -> str:
    return resolve_analysis_path(name)


def _current_state_refresh_id(
    *,
    start: date,
    end: date,
    projects: Sequence[str] | None,
) -> str:
    project_key = ",".join(sorted(projects or ())) if projects else "all"
    return f"current-state:{start.isoformat()}:{end.isoformat()}:{project_key}"


def _machine_analysis_refresh_id(
    *,
    start: date | None,
    end: date | None,
) -> str:
    start_key = start.isoformat() if start is not None else "rolling"
    end_key = end.isoformat() if end is not None else "today"
    return f"machine-analysis:{start_key}:{end_key}"


def _rolling_window(
    *,
    start: date | None,
    end: date | None,
    days: int,
) -> tuple[date, date]:
    """Resolve an optional inclusive rolling analysis window."""
    resolved_end = end or date.today()
    resolved_start = start or (resolved_end - timedelta(days=days - 1))
    return resolved_start, resolved_end


def _promote_operator_day(*, start: date | None, end: date | None) -> dict:
    from lynchpin.substrate.connection import apply_schema, connect, substrate_path
    from lynchpin.substrate.personal import promote_operator_day_rows
    from lynchpin.analysis.active.substrate_promote_status import record_source_status

    resolved_start, resolved_end = _rolling_window(start=start, end=end, days=90)
    refresh_id = f"operator-day:{resolved_start.isoformat()}:{resolved_end.isoformat()}"
    rows = operator_daily_matrix(resolved_start, resolved_end, skip_slow=True)
    with connect(substrate_path()) as conn:
        apply_schema(conn)
        n = promote_operator_day_rows(conn, refresh_id=refresh_id, rows=rows)
        record_source_status(
            conn,
            refresh_id=refresh_id,
            source="operator_day",
            status="ok" if n > 0 else "empty",
            reason=None,
            row_count=n,
            window_start=resolved_start,
            window_end=resolved_end,
        )
    return {"refresh_id": refresh_id, "rows_promoted": n}


CURRENT_STATE_SUBSTRATE_SOURCES = (
    SOURCE_COMMITS,
    SOURCE_FILE_CHANGES,
    SOURCE_SYMBOLS,
    SOURCE_AI_WORK_EVENTS,
    SOURCE_EVIDENCE_GRAPH,
    SOURCE_PR_REVIEW,
    SOURCE_WORK_OBSERVATIONS,
)

MACHINE_ANALYSIS_SUBSTRATE_SOURCES = (
    SOURCE_WORK_OBSERVATIONS,
    SOURCE_MACHINE,
    SOURCE_MACHINE_GPU,
    SOURCE_MACHINE_NETWORK,
    SOURCE_MACHINE_PROCESS_IO_DELTA,
    SOURCE_MACHINE_PROCESS_MEMORY,
    SOURCE_MACHINE_CGROUP_MEMORY,
    SOURCE_MACHINE_KILL_EVENT,
    SOURCE_MACHINE_SERVICE_STATE,
    SOURCE_MACHINE_EXPERIMENTS,
)


def _add_machine_analysis_steps(
    dag: DAG,
    *,
    start: date | None = None,
    end: date | None = None,
    substrate_step: str | None = "substrate_promote",
) -> list[str]:
    substrate_deps = [substrate_step] if substrate_step is not None else []
    command_start, command_end = _rolling_window(start=start, end=end, days=90)
    dag.add(Step(
        "machine_telemetry_analysis",
        fn=lambda: write_machine_telemetry_analysis(Path(_out("machine_telemetry_analysis.json")), start=start, end=end),
        depends_on=substrate_deps,
    ))
    dag.add(Step(
        "machine_episode_analysis",
        fn=lambda: write_machine_episode_analysis(Path(_out("machine_episode_analysis.json")), start=start, end=end),
        depends_on=substrate_deps,
    ))
    dag.add(Step(
        "machine_pressure_incidents",
        fn=lambda: write_machine_pressure_incidents(Path(_out("machine_pressure_incidents.json")), start=start, end=end),
        depends_on=substrate_deps,
    ))
    dag.add(Step(
        "machine_below_analysis",
        fn=lambda: write_below_analysis(Path(_out("machine_below_analysis.json"))),
    ))
    dag.add(Step(
        "machine_below_attribution",
        fn=lambda: write_below_attribution_analysis(Path(_out("machine_below_attribution.json")), start=start, end=end),
        depends_on=["machine_episode_analysis", "machine_below_analysis", "machine_work_observations"],
    ))
    dag.add(Step(
        "machine_below_export_handoff",
        fn=lambda: write_below_export_handoff(Path(_out("machine_below_export_handoff.json")), start=start, end=end),
        depends_on=["machine_below_attribution"],
    ))
    dag.add(Step(
        "machine_context_windows",
        fn=lambda: write_machine_context_analysis(Path(_out("machine_context_windows.json")), start=start, end=end),
        depends_on=["machine_episode_analysis"],
    ))
    dag.add(Step(
        "machine_work_observations",
        fn=lambda: write_work_observation_analysis(Path(_out("machine_work_observations.json")), start=start, end=end),
        depends_on=substrate_deps,
    ))
    dag.add(Step(
        "workflow_mechanics",
        fn=lambda: write_workflow_mechanics_report(Path(_out("workflow_mechanics.json")), start=start, end=end),
        depends_on=["machine_work_observations"],
    ))
    dag.add(Step(
        "keylog_analysis",
        fn=lambda: write_keylog_analysis(
            Path(_out("keylog_analysis.json")),
            start=command_start,
            end=command_end,
        ),
    ))
    dag.add(Step(
        "machine_analysis_feature_frames",
        fn=lambda: write_machine_feature_frames(Path(_out("machine_analysis_feature_frames.json")), start=start, end=end),
        depends_on=substrate_deps,
    ))
    dag.add(Step(
        "machine_mining",
        fn=lambda: write_machine_mining(Path(_out("machine_mining.json")), start=start, end=end),
        depends_on=["machine_analysis_feature_frames"],
    ))
    dag.add(Step(
        "machine_dataset_diagnostics",
        fn=lambda: write_machine_dataset_diagnostics(
            Path(_out("machine_dataset_diagnostics.json")),
            start=start,
            end=end,
        ),
        depends_on=["machine_analysis_feature_frames", "machine_mining"],
    ))
    dag.add(Step(
        "machine_validation_design",
        fn=lambda: write_machine_validation_design(Path(_out("machine_validation_design.json")), start=start, end=end),
        depends_on=["machine_analysis_feature_frames"],
    ))
    dag.add(Step(
        "machine_matched_designs",
        fn=lambda: write_machine_matched_designs(Path(_out("machine_matched_designs.json")), start=start, end=end),
        depends_on=["machine_analysis_feature_frames", "machine_validation_design"],
    ))
    dag.add(Step(
        "machine_negative_controls",
        fn=lambda: write_machine_negative_controls(Path(_out("machine_negative_controls.json")), start=start, end=end),
        depends_on=["machine_matched_designs"],
    ))
    dag.add(Step(
        "machine_comparisons",
        fn=lambda: write_machine_comparisons(Path(_out("machine_comparisons.json")), start=start, end=end),
        depends_on=[
            "machine_mining",
            "machine_dataset_diagnostics",
            "machine_validation_design",
            "machine_matched_designs",
            "machine_negative_controls",
        ],
    ))
    dag.add(Step(
        "machine_work_state_windows",
        fn=lambda: write_machine_work_state_analysis(Path(_out("machine_work_state_windows.json")), start=start, end=end),
        depends_on=["machine_context_windows"],
    ))
    dag.add(Step(
        "command_performance_windows",
        fn=lambda: write_command_performance_analysis(
            Path(_out("command_performance_windows.json")),
            start=command_start,
            end=command_end,
        ),
        depends_on=["machine_work_state_windows"],
    ))
    dag.add(Step(
        "machine_observational_deltas",
        fn=lambda: write_observational_command_deltas(Path(_out("machine_observational_deltas.json")), start=start, end=end),
        depends_on=["command_performance_windows"],
    ))
    dag.add(Step(
        "machine_attribution_candidates",
        fn=lambda: write_machine_attribution_candidates(Path(_out("machine_attribution_candidates.json")), start=start, end=end),
        depends_on=["machine_observational_deltas", "machine_work_observations", "machine_comparisons", "machine_matched_designs"],
    ))
    dag.add(Step(
        "machine_derivation_inventory",
        fn=lambda: write_machine_derivation_inventory(Path(_out("machine_derivation_inventory.json")), start=start, end=end),
    ))
    dag.add(Step(
        "machine_benchmark_plans",
        fn=lambda: write_machine_benchmark_plans(Path(_out("machine_benchmark_plans.json")), start=start, end=end),
        depends_on=["machine_attribution_candidates", "machine_derivation_inventory"],
    ))
    dag.add(Step(
        "machine_benchmark_manifest_bundle",
        fn=lambda: write_machine_benchmark_manifest_bundle(Path(_out("machine_benchmark_manifest_bundle.json")), start=start, end=end),
        depends_on=["machine_benchmark_plans"],
    ))
    dag.add(Step(
        "machine_benchmark_preflight",
        fn=lambda: write_machine_benchmark_preflight(Path(_out("machine_benchmark_preflight.json")), start=start, end=end),
        depends_on=["machine_benchmark_manifest_bundle"],
    ))
    dag.add(Step(
        "machine_support_assessment",
        fn=lambda: write_machine_support_assessment(Path(_out("machine_support_assessment.json")), start=start, end=end),
        depends_on=["machine_benchmark_preflight", "machine_experiment_claims"],
    ))
    dag.add(Step(
        "machine_benchmark_execution_handoff",
        fn=lambda: write_machine_benchmark_execution_handoff(Path(_out("machine_benchmark_execution_handoff.json")), start=start, end=end),
        depends_on=["machine_benchmark_manifest_bundle", "machine_benchmark_preflight", "machine_support_assessment"],
    ))
    dag.add(Step(
        "machine_mechanism_hypotheses",
        fn=lambda: write_machine_mechanisms(Path(_out("machine_mechanism_hypotheses.json")), start=start, end=end),
        depends_on=["machine_support_assessment"],
    ))
    dag.add(Step(
        "machine_instrumentation_gaps",
        fn=lambda: write_machine_instrumentation_gaps(Path(_out("machine_instrumentation_gaps.json")), start=start, end=end),
        depends_on=["machine_support_assessment"],
    ))
    dag.add(Step(
        "machine_calibration_fixtures",
        fn=lambda: write_machine_calibration(Path(_out("machine_calibration_fixtures.json")), start=start, end=end),
    ))
    dag.add(Step(
        "machine_measurement_system",
        fn=lambda: write_machine_measurement_system(Path(_out("machine_measurement_system.json")), start=start, end=end),
        depends_on=["machine_analysis_feature_frames", "machine_experiment_claims", "machine_work_observations"],
    ))
    dag.add(Step(
        "machine_attribution_claims",
        fn=lambda: write_machine_attribution_claims(Path(_out("machine_attribution_claims.json")), start=start, end=end),
        depends_on=["machine_support_assessment", "machine_experiment_claims"],
    ))
    dag.add(Step(
        "machine_assumption_checks",
        fn=lambda: write_machine_assumption_checks(Path(_out("machine_assumption_checks.json")), start=start, end=end),
        depends_on=["machine_attribution_claims"],
    ))
    dag.add(Step(
        "devshell_performance",
        fn=lambda: write_devshell_performance_analysis(
            Path(_out("devshell_performance.json")),
            start=command_start,
            end=command_end,
        ),
        depends_on=["command_performance_windows"],
    ))
    dag.add(Step(
        "machine_observational_baselines",
        fn=lambda: write_machine_observational_baselines(Path(_out("machine_observational_baselines.json")), start=start, end=end),
        depends_on=["machine_telemetry_analysis", "machine_context_windows", "machine_work_state_windows"],
    ))
    dag.add(Step(
        "machine_experiment_claims",
        fn=lambda: write_machine_experiment_claims(Path(_out("machine_experiment_claims.json")), start=start, end=end),
        depends_on=[*substrate_deps, "machine_episode_analysis"],
    ))
    dag.add(Step(
        "machine_experiment_manifest_diagnostics",
        fn=lambda: write_machine_experiment_manifest_diagnostics(
            Path(_out("machine_experiment_manifest_diagnostics.json")),
            start=start,
            end=end,
        ),
    ))
    dag.add(Step(
        "machine_gap_summary",
        fn=lambda: write_gap_summary_analysis(Path(_out("machine_gap_summary.json"))),
        depends_on=substrate_deps,
    ))
    dag.add(Step(
        "machine_analysis_readiness",
        fn=lambda: write_machine_analysis_readiness(Path(_out("machine_analysis_readiness.json")), start=start, end=end),
        depends_on=[
            "machine_telemetry_analysis",
            "machine_below_attribution",
            "machine_below_export_handoff",
            "machine_work_state_windows",
            "command_performance_windows",
            "machine_observational_deltas",
            "machine_attribution_candidates",
            "machine_derivation_inventory",
            "machine_benchmark_plans",
            "machine_benchmark_manifest_bundle",
            "machine_benchmark_preflight",
            "machine_experiment_manifest_diagnostics",
            "machine_support_assessment",
            "machine_benchmark_execution_handoff",
            "machine_mechanism_hypotheses",
            "machine_instrumentation_gaps",
            "machine_calibration_fixtures",
            "machine_measurement_system",
            "machine_attribution_claims",
            "machine_assumption_checks",
            "devshell_performance",
            "machine_observational_baselines",
            "machine_experiment_claims",
            "machine_gap_summary",
            "machine_work_observations",
            "workflow_mechanics",
            "keylog_analysis",
            "machine_analysis_feature_frames",
            "machine_mining",
            "machine_dataset_diagnostics",
            "machine_validation_design",
            "machine_matched_designs",
            "machine_negative_controls",
            "machine_comparisons",
        ],
    ))
    return [
        "machine_telemetry_analysis",
        "machine_episode_analysis",
        "machine_below_analysis",
        "machine_below_attribution",
        "machine_below_export_handoff",
        "machine_context_windows",
        "machine_work_observations",
        "workflow_mechanics",
        "keylog_analysis",
        "machine_analysis_feature_frames",
        "machine_mining",
        "machine_dataset_diagnostics",
        "machine_validation_design",
        "machine_matched_designs",
        "machine_negative_controls",
        "machine_comparisons",
        "machine_work_state_windows",
        "command_performance_windows",
        "machine_observational_deltas",
        "machine_attribution_candidates",
        "machine_derivation_inventory",
        "machine_benchmark_plans",
        "machine_benchmark_manifest_bundle",
        "machine_benchmark_preflight",
        "machine_support_assessment",
        "machine_benchmark_execution_handoff",
        "machine_mechanism_hypotheses",
        "machine_instrumentation_gaps",
        "machine_calibration_fixtures",
        "machine_measurement_system",
        "machine_attribution_claims",
        "machine_assumption_checks",
        "devshell_performance",
        "machine_observational_baselines",
        "machine_experiment_claims",
        "machine_experiment_manifest_diagnostics",
        "machine_gap_summary",
        "machine_analysis_readiness",
    ]


def _add_personal_analysis_steps(
    dag: DAG,
    *,
    start: date | None = None,
    end: date | None = None,
) -> list[str]:
    personal_start, personal_end = _rolling_window(start=start, end=end, days=90)
    dag.add(Step(
        "personal_anomaly_crossref",
        fn=lambda: write_anomaly_crossref_report(Path(_out("anomaly_crossref.json")), start=personal_start, end=personal_end),
    ))
    dag.add(Step(
        "personal_life_phase",
        fn=lambda: write_life_phase_report(Path(_out("life_phase_report.json")), start=personal_start, end=personal_end),
    ))
    dag.add(Step(
        "personal_productivity_predictors",
        fn=lambda: write_productivity_predictors_report(Path(_out("productivity_predictors.json")), start=personal_start, end=personal_end),
    ))
    dag.add(Step(
        "personal_substance_health",
        fn=lambda: write_substance_health_report(Path(_out("substance_health_report.json")), start=personal_start, end=personal_end),
    ))
    dag.add(Step(
        "personal_burnout_warning",
        fn=lambda: write_burnout_warning_report(Path(_out("burnout_warning.json")), start=personal_start, end=personal_end),
    ))
    dag.add(Step(
        "personal_ai_session_efficiency",
        fn=lambda: write_ai_session_efficiency_report(Path(_out("ai_session_efficiency.json")), start=personal_start, end=personal_end),
    ))
    dag.add(Step(
        "personal_operator_day",
        fn=lambda: _promote_operator_day(start=start, end=end),
    ))
    return [
        "personal_anomaly_crossref",
        "personal_life_phase",
        "personal_productivity_predictors",
        "personal_substance_health",
        "personal_burnout_warning",
        "personal_ai_session_efficiency",
        "personal_operator_day",
    ]


def _code_version() -> str:
    """A token that changes when the analysis code changes.

    Under the Nix deployment the package lives at a content-addressed store
    path, so its parent directory is unique per build; in a dev checkout it is
    stable, so use ``materialize --no-memo`` to force a rebuild after editing
    analysis code.
    """

    import lynchpin

    return str(Path(lynchpin.__file__).resolve().parent)


def current_state_dag(
    *,
    start: date,
    end: date,
    projects: Sequence[str] | None = None,
    include_github_frontier: bool = False,
    weak_tags: bool = False,
    persist_weak_tags: bool = False,
) -> DAG:
    """Build the active-project current-state materialization DAG without external-repo prerequisites."""
    dag = DAG("current-state-materialization")
    dag.add(Step(
        "active_project_snapshot",
        fn=lambda: run_active_project_snapshot(
            _out("active_project_snapshot.json"),
            start=start,
            end=end,
            projects=projects,
        ),
    ))
    dag.add(Step(
        "active_code_inventory",
        fn=lambda: run_active_code_inventory(
            _out("active_code_inventory.json"),
            start=start,
            end=end,
            projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
        ),
        depends_on=["active_project_snapshot"],
    ))
    dag.add(Step(
        "active_python_complexity",
        fn=lambda: run_active_python_complexity(
            _out("active_python_complexity.json"),
            start=start,
            end=end,
            projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
        ),
        depends_on=["active_project_snapshot"],
    ))
    dag.add(Step(
        "active_python_import_graph",
        fn=lambda: run_active_python_import_graph(
            _out("active_python_import_graph.json"),
            projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
        ),
        depends_on=["active_project_snapshot"],
    ))
    dag.add(Step(
        "active_rust_workspace_graph",
        fn=lambda: run_active_rust_graph(
            _out("active_rust_workspace_graph.json"),
            start=start,
            end=end,
            projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
            file_changes_file=_out("active_file_change_facts.json"),
        ),
        depends_on=["active_git_facts", "active_project_snapshot"],
    ))
    dag.add(Step(
        "active_git_facts",
        fn=lambda: run_active_git_facts(
            _out("active_commit_facts.json"),
            _out("active_file_change_facts.json"),
            start=start,
            end=end,
            projects=projects,
        ),
    ))
    dag.add(Step(
        "code_history_claims",
        fn=lambda: write_code_history_claims(
            Path(_out("code_history_claims.json")),
            start=start,
            end=end,
        ),
        depends_on=["active_git_facts"],
    ))
    dag.add(Step(
        "active_work_packages",
        fn=lambda: run_active_work_packages(
            _out("active_work_packages.json"),
            start=start,
            end=end,
            projects=projects,
        ),
        depends_on=["active_git_facts"],
    ))
    dag.add(Step(
        "project_velocity_windows",
        fn=lambda: run_project_velocity_windows(
            _out("project_velocity_windows.json"),
            start=start,
            end=end,
            projects=projects,
            commit_facts_file=_out("active_commit_facts.json"),
            work_packages_file=_out("active_work_packages.json"),
        ),
        depends_on=["active_git_facts", "active_work_packages"],
    ))
    dag.add(Step(
        "active_code_hotspots",
        fn=lambda: run_active_hotspots(
            _out("active_code_hotspots.json"),
            start=start,
            end=end,
            projects=projects,
            file_changes_file=_out("active_file_change_facts.json"),
            snapshot_file=_out("active_project_snapshot.json"),
        ),
        depends_on=["active_git_facts", "active_project_snapshot"],
    ))
    dag.add(Step(
        "active_quality_guardrails",
        fn=lambda: run_active_guardrails(
            _out("active_quality_guardrails.json"),
            start=start,
            end=end,
            projects=projects,
            file_changes_file=_out("active_file_change_facts.json"),
            snapshot_file=_out("active_project_snapshot.json"),
        ),
        depends_on=["active_git_facts", "active_project_snapshot"],
    ))
    dag.add(Step(
        "active_structural_findings",
        fn=lambda: run_active_structural_findings(
            _out("active_structural_findings.json"),
            start=start,
            end=end,
            projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
            file_changes_file=_out("active_file_change_facts.json"),
        ),
        depends_on=["active_git_facts", "active_project_snapshot"],
    ))
    dag.add(Step(
        "active_semantic_static_findings",
        fn=lambda: run_active_semantic_static_findings(
            _out("active_semantic_static_findings.json"),
            start=start,
            end=end,
            projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
            file_changes_file=_out("active_file_change_facts.json"),
        ),
        depends_on=["active_git_facts", "active_project_snapshot"],
    ))
    dag.add(Step(
        "active_rust_dependency_hygiene",
        fn=lambda: run_active_rust_dependency_hygiene(
            _out("active_rust_dependency_hygiene.json"),
            start=start,
            end=end,
            projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
        ),
        depends_on=["active_project_snapshot"],
    ))
    dag.add(Step(
        "active_python_dependency_hygiene",
        fn=lambda: run_active_python_dependency_hygiene(
            _out("active_python_dependency_hygiene.json"),
            start=start, end=end, projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
            import_graph_file=_out("active_python_import_graph.json"),
        ),
        depends_on=["active_project_snapshot", "active_python_import_graph"],
    ))
    dag.add(Step(
        "active_symbol_index",
        fn=lambda: run_active_symbol_index(
            _out("active_symbol_index.json"),
            projects=projects,
        ),
        depends_on=["active_project_snapshot"],
    ))
    dag.add(Step(
        "active_symbol_changes",
        fn=lambda: run_active_symbol_diffs(
            _out("active_symbol_changes.json"),
            start=start, end=end, projects=projects,
            symbol_index_file=_out("active_symbol_index.json"),
            commit_facts_file=_out("active_commit_facts.json"),
            snapshot_file=_out("active_project_snapshot.json"),
        ),
        depends_on=["active_symbol_index", "active_git_facts", "active_project_snapshot"],
    ))
    dag.add(Step(
        "active_ci_health",
        fn=lambda: run_active_ci_health(
            _out("active_ci_health.json"),
            start=start, end=end, projects=projects,
            snapshot_file=_out("active_project_snapshot.json"),
            include_runs=include_github_frontier,
        ),
        depends_on=["active_project_snapshot"],
    ))
    dag.add(Step(
        "active_commit_semantics",
        fn=lambda: run_active_commit_semantics(
            _out("active_commit_semantics.json"),
            start=start,
            end=end,
            projects=projects,
        ),
        depends_on=["active_git_facts"],
    ))
    dag.add(Step(
        "active_ai_attribution",
        fn=lambda: run_active_ai_attribution(
            _out("active_ai_attribution.json"),
            start=start, end=end, projects=projects,
        ),
        depends_on=["active_git_facts"],
    ))
    dag.add(Step(
        "current_state_substrate_promote",
        fn=lambda: run_substrate_promote(
            commit_facts_file=_out("active_commit_facts.json"),
            file_changes_file=_out("active_file_change_facts.json"),
            symbol_changes_file=_out("active_symbol_changes.json"),
            ai_attribution_file=_out("active_ai_attribution.json"),
            pr_review_file=_out("active_pr_review_topology.json"),
            refresh_id=_current_state_refresh_id(
                start=start,
                end=end,
                projects=projects,
            ),
            window_start=start,
            window_end=end,
            sources=CURRENT_STATE_SUBSTRATE_SOURCES,
            write_evidence_graph=True,
        ),
        # active_ai_attribution intentionally NOT a hard dep — same rationale
        # as the main substrate_promote step. Polylogue insight failures
        # should degrade only the AI substrate, not block git/symbol.
        depends_on=[
            "active_git_facts",
            "active_symbol_changes",
            "code_history_claims",
        ],
    ))
    dag.add(Step(
        "machine_analysis_substrate_promote",
        fn=lambda: run_substrate_promote(
            commit_facts_file=_out("active_commit_facts.json"),
            file_changes_file=_out("active_file_change_facts.json"),
            symbol_changes_file=_out("active_symbol_changes.json"),
            pr_review_file=_out("active_pr_review_topology.json"),
            refresh_id=_machine_analysis_refresh_id(start=start, end=end),
            window_start=start,
            window_end=end,
            sources=MACHINE_ANALYSIS_SUBSTRATE_SOURCES,
            write_evidence_graph=False,
        ),
    ))
    machine_steps = _add_machine_analysis_steps(
        dag,
        start=start,
        end=end,
        substrate_step="machine_analysis_substrate_promote",
    )
    dag.add(Step(
        "current_state_operator_day",
        fn=lambda: _promote_operator_day(start=start, end=end),
    ))
    current_state_deps = [
        "active_project_snapshot",
        "active_code_inventory",
        "active_python_complexity",
        "active_python_import_graph",
        "active_git_facts",
        "code_history_claims",
        "active_rust_workspace_graph",
        "active_work_packages",
        "project_velocity_windows",
        "active_code_hotspots",
        "active_quality_guardrails",
        "active_structural_findings",
        "active_semantic_static_findings",
        "active_rust_dependency_hygiene",
        "active_python_dependency_hygiene",
        "active_symbol_index",
        "active_symbol_changes",
        "active_ci_health",
        "active_commit_semantics",
        "active_ai_attribution",
        *machine_steps,
        "current_state_operator_day",
    ]
    if include_github_frontier:
        dag.add(Step(
            "active_github_frontier",
            fn=lambda: run_active_github_frontier(
                _out("active_github_frontier.json"),
                start=start,
                end=end,
                projects=projects,
                snapshot_file=_out("active_project_snapshot.json"),
                work_packages_file=_out("active_work_packages.json"),
            ),
            depends_on=["active_project_snapshot", "active_work_packages"],
        ))
        current_state_deps.append("active_github_frontier")
    dag.add(Step(
        "current_state_context",
        fn=lambda: run_current_state_analysis(
            start=start,
            end=end,
            out_file=_out("current_state_context_pack.json"),
            markdown_out=_out("current_state_context_pack.md"),
            projects=projects,
            include_github_frontier=include_github_frontier,
            weak_tags=weak_tags,
            persist_weak_tags=persist_weak_tags,
        ),
        depends_on=current_state_deps,
    ))
    dag.add(Step(
        "current_state_narrative",
        fn=lambda: _run_narrative(
            start=start, end=end, projects=projects,
        ),
        depends_on=["current_state_context"],
    ))
    return dag


def machine_analysis_dag(
    *,
    start: date | None = None,
    end: date | None = None,
) -> DAG:
    """Build the source-selected machine-analysis materialization DAG."""
    dag = DAG("machine-analysis-materialization")
    machine_start, machine_end = _rolling_window(start=start, end=end, days=90)
    dag.add(Step(
        "machine_analysis_substrate_promote",
        fn=lambda: run_substrate_promote(
            commit_facts_file=_out("active_commit_facts.json"),
            file_changes_file=_out("active_file_change_facts.json"),
            symbol_changes_file=_out("active_symbol_changes.json"),
            pr_review_file=_out("active_pr_review_topology.json"),
            refresh_id=_machine_analysis_refresh_id(start=start, end=end),
            window_start=machine_start,
            window_end=machine_end,
            sources=MACHINE_ANALYSIS_SUBSTRATE_SOURCES,
            write_evidence_graph=False,
        ),
    ))
    _add_machine_analysis_steps(
        dag,
        start=start,
        end=end,
        substrate_step="machine_analysis_substrate_promote",
    )
    return dag


def _run_narrative(
    *,
    start: date,
    end: date,
    projects: Sequence[str] | None = None,
) -> dict[str, Any]:
    from ..graph.narrative import narrate
    narrate(
        start=start, end=end, projects=projects,
        out=str(resolve_analysis_path("current_state_narrative.md")),
        json_out=str(resolve_analysis_path("current_state_narrative.json")),
    )
    return {"status": "ok"}


def _compute_sinex_temporal(repo: str, out_path: str) -> object:
    monthly = sinex_temporal.compute_monthly_velocity(repo)
    crate_growth = sinex_temporal.compute_crate_growth(repo)
    stats = sinex_temporal.compute_sinex_stats(repo)
    payload = {
        'monthly_velocity': monthly,
        'crate_growth': crate_growth,
        'stats': stats,
    }
    save_json(resolve_analysis_path(out_path), payload)
    return payload
