"""Project-level repomix bundle generation."""
from __future__ import annotations

from collections.abc import Callable, Sequence
import datetime as dt
import json
import os
import shlex
import shutil
import subprocess
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path

from ...core.io import write_text_if_changed
from ...core.projects import project_profiles

BUNDLE_ROOT = Path("/realm/project/_context-project-bundles")
DEFAULT_LOGS_COUNT = 30
INDEX_SCHEMA = "project-context-bundle-index-v1"
MANIFEST_SCHEMA = "project-context-bundle-v1"
DEFAULT_IGNORE_PATTERNS = (
    ".git/**",
    ".direnv/**",
    ".claude/history-summaries/**",
    ".claude/scratch/**",
    ".venv/**",
    "venv/**",
    "node_modules/**",
    "target/**",
    "dist/**",
    "build/**",
    "coverage/**",
    ".cache/**",
    "artefacts/**",
    "result/**",
    "out/**",
)


@dataclass(frozen=True)
class ProjectSpec:
    name: str
    path: Path
    extra_ignore: tuple[str, ...] = ()


@dataclass(frozen=True)
class GitState:
    branch: str
    commit: str
    dirty: bool


@dataclass(frozen=True)
class BundleArtifact:
    name: str
    variant: str
    path: Path
    size_bytes: int
    command: list[str]


PROJECT_SPECS = {
    name: ProjectSpec(profile.name, profile.path, profile.extra_ignore)
    for name, profile in project_profiles().items()
}
PROJECT_SPECS["sinex-target-vision"] = ProjectSpec(
    "sinex-target-vision",
    Path("/realm/project/sinex-ultimate-vision").resolve(),
    extra_ignore=(
        "archive/**",
        "generated/**",
        "sources/raw/**",
        "sources/normalized/**",
        "sources/snapshots/**",
    ),
)
LogFn = Callable[[str], None]


def _noop(_message: str) -> None:
    pass


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")


def run_command(cmd: Sequence[str], *, cwd: Path | None = None) -> subprocess.CompletedProcess[str]:
    env = os.environ.copy()
    env.setdefault("NO_COLOR", "1")
    return subprocess.run(
        list(cmd),
        cwd=str(cwd) if cwd else None,
        text=True,
        capture_output=True,
        encoding="utf-8",
        errors="replace",
        env=env,
    )


def require_repomix() -> str:
    repomix_bin = shutil.which("repomix")
    if repomix_bin is None:
        raise RuntimeError("repomix is required for project bundle generation")
    return repomix_bin


def repomix_version(repomix_bin: str) -> str:
    result = run_command([repomix_bin, "--version"])
    if result.returncode == 0 and result.stdout.strip():
        return result.stdout.strip()
    return "unknown"


def git_state(repo: Path) -> GitState:
    branch = run_command(["git", "rev-parse", "--abbrev-ref", "HEAD"], cwd=repo)
    commit = run_command(["git", "rev-parse", "HEAD"], cwd=repo)
    status = run_command(["git", "status", "--short"], cwd=repo)
    if branch.returncode != 0 or commit.returncode != 0 or status.returncode != 0:
        raise RuntimeError(f"failed to inspect git state for {repo}")
    return GitState(
        branch=branch.stdout.strip(),
        commit=commit.stdout.strip(),
        dirty=bool(status.stdout.strip()),
    )


def project_ignore_patterns(spec: ProjectSpec) -> str:
    patterns = list(DEFAULT_IGNORE_PATTERNS)
    patterns.extend(spec.extra_ignore)
    return ",".join(patterns)


def bundle_header(
    *,
    spec: ProjectSpec,
    git: GitState,
    generated_at: str,
    variant: str,
    include_diffs: bool,
    logs_count: int,
) -> str:
    return "\n".join(
        (
            f"Project: {spec.name}",
            f"Source path: {spec.path}",
            f"Generated at: {generated_at}",
            f"Variant: {variant}",
            f"Git branch: {git.branch}",
            f"Git commit: {git.commit}",
            f"Dirty worktree: {'yes' if git.dirty else 'no'}",
            f"Git log entries included: {logs_count}",
            f"Working tree diff included: {'yes' if include_diffs else 'no'}",
            "Generated by lynchpin.analysis.projects.bundles via repomix.",
        )
    )


def build_repomix_command(
    *,
    repomix_bin: str,
    output_path: Path,
    spec: ProjectSpec,
    git: GitState,
    generated_at: str,
    variant: str,
    include_diffs: bool,
    logs_count: int,
    compressed: bool,
) -> list[str]:
    command = [
        repomix_bin,
        ".",
        "--quiet",
        "--no-security-check",
        "--style",
        "markdown",
        "--parsable-style",
        "--include-logs",
        "--include-logs-count",
        str(logs_count),
        "--header-text",
        bundle_header(
            spec=spec,
            git=git,
            generated_at=generated_at,
            variant=variant,
            include_diffs=include_diffs,
            logs_count=logs_count,
        ),
        "--ignore",
        project_ignore_patterns(spec),
        "--output",
        str(output_path),
    ]
    if not compressed:
        command.append("--output-show-line-numbers")
    if include_diffs:
        command.append("--include-diffs")
    if compressed:
        command.extend(["--compress", "--remove-empty-lines"])
    return command


def run_repomix_bundle(
    *,
    repomix_bin: str,
    output_path: Path,
    spec: ProjectSpec,
    git: GitState,
    generated_at: str,
    variant: str,
    include_diffs: bool,
    logs_count: int,
    compressed: bool,
) -> BundleArtifact:
    command = build_repomix_command(
        repomix_bin=repomix_bin,
        output_path=output_path,
        spec=spec,
        git=git,
        generated_at=generated_at,
        variant=variant,
        include_diffs=include_diffs,
        logs_count=logs_count,
        compressed=compressed,
    )
    result = run_command(command, cwd=spec.path)
    if result.returncode != 0:
        details = (result.stderr or result.stdout or "repomix failed").strip()
        raise RuntimeError(f"{spec.name}: {details}")
    if not output_path.exists():
        raise RuntimeError(f"{spec.name}: expected bundle output was not written: {output_path}")
    return BundleArtifact(
        name=output_path.name,
        variant=variant,
        path=output_path,
        size_bytes=output_path.stat().st_size,
        command=command,
    )


def render_project_readme(manifest: dict[str, object]) -> str:
    outputs = manifest["outputs"]
    git = manifest["git"]
    lines = [
        f"# {manifest['project']}",
        "",
        f"- Source: `{manifest['source_path']}`",
        f"- Generated: `{manifest['generated_at']}`",
        f"- Branch: `{git['branch']}`",
        f"- Commit: `{git['commit']}`",
        f"- Dirty worktree: `{git['dirty']}`",
        f"- Repomix: `{manifest['repomix_version']}`",
        "",
        "## Outputs",
    ]
    for output in outputs:
        lines.append(
            f"- `{output['name']}`: `{output['variant']}` bundle, `{output['size_bytes']}` bytes"
        )
    return "\n".join(lines) + "\n"


def render_root_readme(index: dict[str, object]) -> str:
    lines = [
        "# Project Bundles",
        "",
        f"- Generated: `{index['generated_at']}`",
        f"- Output root: `{index['output_root']}`",
        f"- Repomix: `{index['repomix_version']}`",
        "",
        "## Projects",
    ]
    for project in index["projects"]:
        lines.append(f"- `{project['project']}`: `{project['status']}`")
    return "\n".join(lines) + "\n"


def generate_project_bundle(
    *,
    spec: ProjectSpec,
    output_root: Path,
    repomix_bin: str,
    repomix_build: str,
    include_diffs: bool,
    logs_count: int,
    include_compressed: bool,
) -> dict[str, object]:
    if not spec.path.exists():
        return {
            "project": spec.name,
            "source_path": str(spec.path),
            "status": "missing",
        }

    output_root.mkdir(parents=True, exist_ok=True)
    generated_at = utc_now()
    git = git_state(spec.path)
    temp_dir = Path(tempfile.mkdtemp(prefix=f".{spec.name}-", dir=str(output_root)))
    target_dir = output_root / spec.name

    try:
        outputs: list[BundleArtifact] = []
        outputs.append(
            run_repomix_bundle(
                repomix_bin=repomix_bin,
                output_path=temp_dir / f"{spec.name}-bundle.md",
                spec=spec,
                git=git,
                generated_at=generated_at,
                variant="full",
                include_diffs=include_diffs,
                logs_count=logs_count,
                compressed=False,
            )
        )
        if include_compressed:
            outputs.append(
                run_repomix_bundle(
                    repomix_bin=repomix_bin,
                    output_path=temp_dir / f"{spec.name}-bundle-compressed.md",
                    spec=spec,
                    git=git,
                    generated_at=generated_at,
                    variant="compressed",
                    include_diffs=include_diffs,
                    logs_count=logs_count,
                    compressed=True,
                )
            )

        manifest = {
            "schema_generation": MANIFEST_SCHEMA,
            "project": spec.name,
            "source_path": str(spec.path),
            "output_root": str(target_dir),
            "bundle_dir": str(target_dir),
            "generated_at": generated_at,
            "status": "generated",
            "git": asdict(git),
            "repomix_version": repomix_build,
            "outputs": [
                {
                    "name": output.name,
                    "variant": output.variant,
                    "path": str(target_dir / output.name),
                    "size_bytes": output.size_bytes,
                    "command": shlex.join(
                        [
                            str(target_dir / output.name) if part == str(output.path) else part
                            for part in output.command
                        ]
                    ),
                }
                for output in outputs
            ],
        }
        write_text_if_changed(
            temp_dir / "manifest.json",
            json.dumps(manifest, indent=2, sort_keys=True) + "\n",
        )
        write_text_if_changed(temp_dir / "README.md", render_project_readme(manifest))

        if target_dir.exists():
            shutil.rmtree(target_dir)
        temp_dir.rename(target_dir)
        return manifest
    finally:
        if temp_dir.exists():
            shutil.rmtree(temp_dir, ignore_errors=True)


def select_projects(requested: Sequence[str] | None) -> list[ProjectSpec]:
    if not requested:
        return list(PROJECT_SPECS.values())
    unknown = [name for name in requested if name not in PROJECT_SPECS]
    if unknown:
        available = ", ".join(PROJECT_SPECS)
        raise ValueError(f"unknown projects: {', '.join(unknown)}; available: {available}")
    return [PROJECT_SPECS[name] for name in requested]


def build_project_bundles(
    *,
    project_names: Sequence[str] | None = None,
    output_root: Path = BUNDLE_ROOT,
    logs_count: int = DEFAULT_LOGS_COUNT,
    include_diffs: bool = False,
    include_compressed: bool = True,
    log: LogFn | None = None,
) -> dict[str, object]:
    if log is None:
        log = _noop
    repomix_bin = require_repomix()
    repomix_build = repomix_version(repomix_bin)
    selected = select_projects(project_names)
    output_root = output_root.resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    manifests: list[dict[str, object]] = []
    for spec in selected:
        manifest = generate_project_bundle(
            spec=spec,
            output_root=output_root,
            repomix_bin=repomix_bin,
            repomix_build=repomix_build,
            include_diffs=include_diffs,
            logs_count=logs_count,
            include_compressed=include_compressed,
        )
        manifests.append(manifest)
        log(f"{spec.name}: {manifest['status']}")

    index = {
        "schema_generation": INDEX_SCHEMA,
        "generated_at": utc_now(),
        "output_root": str(output_root),
        "repomix_version": repomix_build,
        "projects": manifests,
    }
    write_text_if_changed(output_root / "index.json", json.dumps(index, indent=2, sort_keys=True) + "\n")
    write_text_if_changed(output_root / "README.md", render_root_readme(index))
    return index
