"""Tests for the in-Lynchpin title rules classifier.

Pins the fallback behavior that fires when the upstream GPT-built
classmap returns None for a (app, normalized_title) hash. Recovers
~30 percentage points of title-classification hit-rate by handling
the dominant 2026 misses: kitty + project-slug, Claude Code session
sentinels, and topic slugs.
"""
from __future__ import annotations

from lynchpin.sources.title_metadata_rules import classify_title_via_rules


def test_kitty_project_slug_canonical():
    c = classify_title_via_rules("kitty", "sinex", "sinex")
    assert c is not None
    assert c.classification_source == "rules-local"
    assert c.activity == "reading_code"
    assert c.mode == "coding"
    assert c.subject == "sinex"


def test_kitty_project_slug_alias():
    c = classify_title_via_rules("kitty", "lynchpin", "lynchpin")
    assert c is not None
    assert c.subject == "sinity-lynchpin"


def test_kitty_polylogue_prefix_subproject_resolves():
    c = classify_title_via_rules("kitty", "polylogue-845-daemon", "polylogue-845-daemon")
    assert c is not None
    assert c.subject == "polylogue"


def test_kitty_unknown_single_token_is_none():
    # Single token that isn't a project slug → no match
    assert classify_title_via_rules("kitty", "totallyrandomstring", "totallyrandomstring") is None
    # Two-token slug → no match (below the 3-token threshold for seed-slug rule)
    assert classify_title_via_rules("kitty", "totally-random", "totally-random") is None


def test_kitty_project_in_foot_terminal_too():
    c = classify_title_via_rules("foot", "sinnix", "sinnix")
    assert c is not None
    assert c.subject == "sinnix"


def test_claude_code_caveat_prefix_classified():
    raw = "<local-command-caveat>Caveat: The messages below were generated by /loop"
    c = classify_title_via_rules("kitty", raw, raw)
    assert c is not None
    assert c.is_ai_tool is True
    assert c.tool == "claude-code"
    assert c.activity == "chatting_work"


def test_start_coding_session_classified_as_claude_code():
    c = classify_title_via_rules("kitty", "Start coding session", "Start coding session")
    assert c is not None
    assert c.tool == "claude-code"
    assert c.activity == "chatting_work"


def test_codex_lifecycle_marker_attributed_to_codex_not_claude_code():
    """`codex` and `codex resume --last` are Codex sessions. Earlier the
    blanket lifecycle rule tagged them as claude-code (11k+ events
    mis-attributed across the May 2026 window)."""
    for title in ("codex", "codex resume --last"):
        c = classify_title_via_rules("kitty", title, title)
        assert c is not None, f"expected match for {title!r}"
        assert c.tool == "codex", f"{title!r} should be codex, got {c.tool!r}"
        assert c.is_ai_tool is True


def test_topic_slug_pattern_classified():
    # Many-dash slug, all lowercase — looks like an agent topic name.
    c = classify_title_via_rules("kitty", "sinex-horizon-2-plan", "sinex-horizon-2-plan")
    # Prefix rule fires first → sinex project. The seed-slug rule is fallback.
    assert c is not None
    assert c.subject == "sinex"


def test_topic_slug_unmatched_to_project():
    # Doesn't match a project prefix, but matches >=4-token dashed slug
    c = classify_title_via_rules("kitty", "evidence-graph-walk-design-v2", "evidence-graph-walk-design-v2")
    assert c is not None
    assert c.activity == "planning"
    assert c.mode == "planning"


def test_short_random_title_unmatched():
    # Short, no project, no sentinel — must NOT match.
    assert classify_title_via_rules("kitty", "vim foo.py", "vim foo.py") is None


def test_browser_app_does_not_get_project_rule():
    # Project-slug rule is kitty/foot only — don't mis-classify a browser tab.
    assert classify_title_via_rules("firefox", "sinex", "sinex") is None


def test_empty_inputs_return_none():
    assert classify_title_via_rules("", "x", "x") is None
    assert classify_title_via_rules("kitty", "", "") is None


def test_three_token_kebab_slug_classified():
    # "phased-issue-closure" — 3 tokens, 2 dashes. Should now match (seed slug).
    c = classify_title_via_rules("kitty", "phased-issue-closure", "phased-issue-closure")
    assert c is not None
    assert c.activity == "planning"


def test_seed_slug_rule_only_fires_for_terminal_apps():
    """Custom apps like 'scratchpad-terminal' have hyphenated names that
    look like kebab slugs. The seed-slug rule must NOT fire for them —
    otherwise it tags app self-identifiers as planning activity."""
    assert classify_title_via_rules(
        "scratchpad-terminal", "sinnix-captured-shell", "sinnix-captured-shell"
    ) is None
    assert classify_title_via_rules(
        "my-custom-app", "some-three-token-slug", "some-three-token-slug"
    ) is None


def test_lynchpin_prefix_alias_resolves():
    # "lynchpin-implementation-plan" — lynchpin is an alias for sinity-lynchpin
    c = classify_title_via_rules("kitty", "lynchpin-implementation-plan", "lynchpin-implementation-plan")
    assert c is not None
    assert c.subject == "sinity-lynchpin"


def test_claude_code_topic_sentence_classified():
    c = classify_title_via_rules("kitty", "Create schema inventory document", "Create schema inventory document")
    assert c is not None
    assert c.tool == "claude-code"
    assert c.confidence == 0.5  # heuristic confidence


def test_topic_sentence_only_for_terminal_apps():
    # Firefox tab title can also look like a sentence — must NOT match this rule
    assert classify_title_via_rules("firefox", "Create schema inventory document", "Create schema inventory document") is None


def test_topic_sentence_too_short_no_match():
    assert classify_title_via_rules("kitty", "Hi all", "Hi all") is None


def test_topic_sentence_too_long_no_match():
    long_title = "Create " + "very " * 30 + "long sentence"
    assert classify_title_via_rules("kitty", long_title, long_title) is None
