"""Samsung Health source facade.

Reads processed JSONL files under /realm/data/exports/health/processed/.
Run `python -m lynchpin.cli.process_health` to refresh from raw exports.

Sleep data is in the separate `sleep` module.
"""

from __future__ import annotations

from .health_daily import daily_health_summary, daily_heart_rate, daily_stress
from .health_loaders import (
    activity_summaries,
    calorie_burns,
    daily_steps,
    daily_vitality,
    ecg_measurements,
    floors_climbed,
    heart_rate_measurements,
    hrv_measurements,
    mood_entries,
    movement_records,
    nap_sessions,
    respiratory_rate,
    skin_temperature,
    snoring_records,
    spo2_measurements,
    stress_measurements,
    weight_measurements,
)
from .health_models import (
    ActivityDaySummary,
    CalorieBurn,
    DailyHealthSummary,
    DailyHeartRateSummary,
    DailyStressSummary,
    ECGMeasurement,
    FloorClimbed,
    HRVMeasurement,
    HeartRateMeasurement,
    MoodEntry,
    MovementRecord,
    NapSession,
    RespiratoryMeasurement,
    SkinTemperature,
    SnoringRecord,
    SpO2Measurement,
    StepDay,
    StressMeasurement,
    VitalityDay,
    WeightMeasurement,
)

__all__ = [
    "ActivityDaySummary",
    "CalorieBurn",
    "DailyHealthSummary",
    "DailyHeartRateSummary",
    "DailyStressSummary",
    "ECGMeasurement",
    "FloorClimbed",
    "HRVMeasurement",
    "HeartRateMeasurement",
    "MoodEntry",
    "MovementRecord",
    "NapSession",
    "RespiratoryMeasurement",
    "SkinTemperature",
    "SnoringRecord",
    "SpO2Measurement",
    "StepDay",
    "StressMeasurement",
    "VitalityDay",
    "WeightMeasurement",
    "activity_summaries",
    "calorie_burns",
    "daily_health_summary",
    "daily_heart_rate",
    "daily_steps",
    "daily_stress",
    "daily_vitality",
    "ecg_measurements",
    "floors_climbed",
    "heart_rate_measurements",
    "hrv_measurements",
    "mood_entries",
    "movement_records",
    "nap_sessions",
    "respiratory_rate",
    "skin_temperature",
    "snoring_records",
    "spo2_measurements",
    "stress_measurements",
    "weight_measurements",
]
